version: '3'

services:
  backend:
    build: ./backend/.
    ports:
      - "3000:3000"
    volumes:
      - "./backend:/backend"
    command: "npm run dev"
    env_file:
      - .env
    links:
      - "mysql:mysql"
    depends_on:
      - mysql
  frontend:
    build: ./frontend/.
    ports:
      - "3001:3001"
    volumes:
      - "./frontend:/frontend"
    command: "npm run start"
    links:
      - "backend:backend"
    depends_on:
      - backend
  mysql:
    image: mysql:5.6
    env_file:
      - .env
    volumes:
      - datavolume:/var/lib/mysql
  phpmyadmin:
    image: corbinu/docker-phpmyadmin
    ports:
      - "8081:80"
    links:
      - mysql
    depends_on:
      - mysql

volumes:
  datavolume:
